// Generated by gencpp from file msgs/Home.msg
// DO NOT EDIT!


#ifndef MSGS_MESSAGE_HOME_H
#define MSGS_MESSAGE_HOME_H

#include <ros/service_traits.h>


#include <msgs/HomeRequest.h>
#include <msgs/HomeResponse.h>


namespace msgs
{

struct Home
{

typedef HomeRequest Request;
typedef HomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Home
} // namespace msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::msgs::Home > {
  static const char* value()
  {
    return "315d885f8f6e90abb232f2881df249a2";
  }

  static const char* value(const ::msgs::Home&) { return value(); }
};

template<>
struct DataType< ::msgs::Home > {
  static const char* value()
  {
    return "msgs/Home";
  }

  static const char* value(const ::msgs::Home&) { return value(); }
};


// service_traits::MD5Sum< ::msgs::HomeRequest> should match 
// service_traits::MD5Sum< ::msgs::Home > 
template<>
struct MD5Sum< ::msgs::HomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::msgs::Home >::value();
  }
  static const char* value(const ::msgs::HomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs::HomeRequest> should match 
// service_traits::DataType< ::msgs::Home > 
template<>
struct DataType< ::msgs::HomeRequest>
{
  static const char* value()
  {
    return DataType< ::msgs::Home >::value();
  }
  static const char* value(const ::msgs::HomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::msgs::HomeResponse> should match 
// service_traits::MD5Sum< ::msgs::Home > 
template<>
struct MD5Sum< ::msgs::HomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::msgs::Home >::value();
  }
  static const char* value(const ::msgs::HomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::msgs::HomeResponse> should match 
// service_traits::DataType< ::msgs::Home > 
template<>
struct DataType< ::msgs::HomeResponse>
{
  static const char* value()
  {
    return DataType< ::msgs::Home >::value();
  }
  static const char* value(const ::msgs::HomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MSGS_MESSAGE_HOME_H
